issuer: http://localhost:{{ .Env.DEX_PORT }}/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: cen-starter
    secret: cen-dev-secret
    redirectURIs:
      - http://localhost:{{ .Env.OAUTH_PROXY_PORT }}/oauth2/callback
    name: CEN Starter (dev)

oauth2:
  skipApprovalScreen: true

enablePasswordDB: true

staticPasswords:
  - email: admin@example.com
    username: admin
    userID: 11111111-1111-1111-1111-111111111111
    hash: "$2a$10$BzSOn93F9r70qJMCj.LdT.okHPksKyUC4R.doWwm4dQ/kBREqdUhq"
